# Generated by Django 5.1.4 on 2024-12-19 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('THB', 'Thai Baht'), ('USD', 'US Dollar'), ('AUD', 'Australian Dollar'), ('HKD', 'Hong Kong Dollar'), ('CAD', 'Canadian Dollar'), ('NZD', 'New Zealand Dollar'), ('SGD', 'Singapore Dollar'), ('EUR', 'Euro'), ('HUF', 'Hungarian Forint'), ('CHF', 'Swiss Franc'), ('GBP', 'British Pound'), ('UAH', 'Ukrainian Hryvnia'), ('JPY', 'Japanese Yen'), ('CZK', 'Czech Koruna'), ('DKK', 'Danish Krone'), ('ISK', 'Icelandic Krona'), ('NOK', 'Norwegian Krone'), ('SEK', 'Swedish Krona'), ('HRK', 'Croatian Kuna'), ('RON', 'Romanian Leu'), ('BGN', 'Bulgarian Lev'), ('TRY', 'Turkish Lira'), ('ILS', 'Israeli New Shekel'), ('CLP', 'Chilean Peso'), ('PHP', 'Philippine Peso'), ('MXN', 'Mexican Peso'), ('ZAR', 'South African Rand'), ('BRL', 'Brazilian Real'), ('MYR', 'Malaysian Ringgit'), ('RUB', 'Russian Ruble'), ('IDR', 'Indonesian Rupiah'), ('INR', 'Indian Rupee'), ('KRW', 'South Korean Won'), ('CNY', 'Chinese Yuan'), ('XDR', 'Special Drawing Rights (SDR)'), ('AFN', 'Afghan Afghani'), ('ALL', 'Albanian Lek'), ('AMD', 'Armenian Dram'), ('AOA', 'Angolan Kwanza'), ('BAM', 'Bosnia-Herzegovina Convertible Mark'), ('BSD', 'Bahamian Dollar'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CHF', 'Swiss Franc'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('NZD', 'New Zealand Dollar'), ('PLN', 'Polish Zloty')], max_length=100)),
                ('wallet_address', models.CharField(editable=False, max_length=40, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
