# Generated by Django 5.1.4 on 2024-12-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_wallet_unique_wallet_per_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'DEPOSIT'), ('WITHDRAWL', 'WITHDRAWL'), ('TRANSFER', 'TRANSFER')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
